name: continuous-integration

on:

push:

branches:

- main

jobs:

lint-and-jest:

    runs-on: ubuntu-latest

    name: lint-and-jest

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run ESLint (Run ESLint)

    - run: npm run test (Run Jest)
